version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - payload_data:/app/data
      - media_uploads:/app/public/media
    env_file:
      - .env
    restart: unless-stopped

volumes:
  payload_data:
  media_uploads:
